---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: meital-wordpress-storage
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer  

---  
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: wordpress-pvc
  namespace: meitaltal  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 1Gi  
  storageClassName: manual
  storageClassName: meital-wordpress-storage

