apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: wordpress-pv-meitaltal  
  namespace: meitaltal
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual  
  hostPath:  
    path: /home/ec2-user/data/wordpress
  claimRef:
    namespace: meitaltal
    name: wordpress-pvc 
  
---  
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: wordpress-pvc
  namespace: meitaltal  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 1Gi  
  storageClassName: manual
  volumeName: wordpress-pv-meitaltal
