---
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: wordpress  
  namespace: meitaltal
spec:  
  replicas: 2  
  selector:  
    matchLabels:  
      app: wordpress  
  template:  
    metadata:  
      labels:  
        app: wordpress  
    spec: 
      imagePullSecrets:
        - name: ecr-secret 
      containers:  
      - name: wordpress  
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/meitaltal/k8s-workshop:wordpress-latest  
        ports:  
        - containerPort: 80  
          name: wordpress  
        volumeMounts:  
        - name: wp-data  
          mountPath: /var/www/html  
        env:  
        - name: WORDPRESS_DB_HOST  
          value: mysql-service.meitaltal.svc.cluster.local  
        - name: WORDPRESS_DB_PASSWORD  
          valueFrom:  
            secretKeyRef:  
              name: mysql-secret  
              key: MYSQL_ROOT_PASSWORD  
        - name: WORDPRESS_DB_USER  
          value: root  
        - name: WORDPRESS_DB_NAME  
          value: wordpress  
      volumes:  
      - name: wp-data  
        persistentVolumeClaim:  
          claimName: wordpress-pvc  
