apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: meital-wordpress-pv  
  namespace: meitaltal
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual  
  hostPath:  
    path: /mnt/data/wordpress 
  
---  
apiVersion: v1  
kind: PersistentVolumeClaim  
metadata:  
  name: wordpress-pvc
  namespace: meitaltal  
spec:  
  accessModes:  
    - ReadWriteOnce  
  resources:  
    requests:  
      storage: 1Gi  
  storageClassName: manual
