apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secret  
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque  
data:  
  MYSQL_ROOT_PASSWORD: d29yZHByZXNzCg==
