apiVersion: v2
name: wordpress-stack
description: A modular Helm chart to deploy WordPress, MySQL, and monitoring (Prometheus & Grafana) with Ingress or ELB exposure options
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    repository: "https://kubernetes.github.io/ingress-nginx"
    version: "4.10.1"
    condition: global.exposure=ingress
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "45.0.0"
    condition: monitoring.enabled  