# Default namespace for all resources deployed by this chart
namespace: meitaltal

# Global settings affecting all components
global:
  exposure: "ingress"  
  storageClassName: "ebs-sc-nitzanim"  
  ingressClassName: "meitaltal"  

# MySQL database configuration
mysql:
  enabled: true
  image: "992382545251.dkr.ecr.us-east-1.amazonaws.com/meitaltal/k8s-workshop:mysql-8.0.27"
  storageSize: "5Gi"

# WordPress application configuration
wordpress:
  enabled: true
  replicaCount: 2
  image: "992382545251.dkr.ecr.us-east-1.amazonaws.com/meitaltal/k8s-workshop:wordpress-latest"
  storageSize: "1Gi"
  ingress:
    host: "acf3314c8225e48fdbc4f011f68a257b-1202305726.us-east-1.elb.amazonaws.com"

# Prometheus & Grafana configuration
monitoring:
  enabled: true
  prometheus:
    fullnameOverride: "kube-prom-stack"
  grafana:
    grafana.ini:
      server:
        root_url: "http://acf3314c8225e48fdbc4f011f68a257b-1202305726.us-east-1.elb.amazonaws.com/grafana"
        serve_from_sub_path: true

# Settings for the NGINX Ingress Controller (used when global.exposure is "ingress")
ingress-nginx:
  controller:
    ingressClassResource:
      name: "meitaltal"