{{- if and .Values.monitoring.enabled (eq .Values.global.exposure "elb") }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: {{ .Values.monitoring.prometheus.fullnameOverride }}
    app.kubernetes.io/name: grafana
  ports:
  - name: grafana-port
    port: 3000
    targetPort: 3000
    protocol: TCP
{{- end }}