{{- if .Values.mysql.enabled }}
apiVersion: v1  
kind: Service  
metadata:  
  name: mysql-service  
  namespace: {{ .Values.namespace }}
spec:  
  ports:  
  - port: 3306  
    protocol: TCP  
  selector:  
    app: mysql
{{- end }}